- name: Desplegar la página web en Docker con Apache y MySQL
  hosts: aws_instance  # Asegúrate de que este grupo esté definido en tu inventario
  become: yes

  tasks:
    - name: Comprobar si Docker está instalado
      command: docker --version
      register: docker_installed
      failed_when: "'Docker version' not in docker_installed.stdout"

    - name: Instalar Docker (si no está instalado)
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_installed is failed

    - name: Instalar Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Iniciar y habilitar Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Crear el directorio para Docker Compose
      file:
        path: /home/ubuntu/docker-website
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Crear archivo docker-compose.yml
      copy:
        dest: /home/ubuntu/docker-website/docker-compose.yml
        content: |
          version: '3'
          services:
            web:
              build: .
              container_name: php_apache_server
              volumes:
                - ./University:/var/www/html/
              ports:
                - "8080:80"
              depends_on:
                - db
            db:
              image: mysql:5.7
              container_name: mysql_db
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"  # Usar variables de entorno o Ansible Vault
                MYSQL_DATABASE: "{{ mysql_database }}"
                MYSQL_USER: "{{ mysql_user }}"
                MYSQL_PASSWORD: "{{ mysql_password }}"
              ports:
                - "3306:3306"
              volumes:
                - db_data:/var/lib/mysql
                - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          volumes:
            db_data:
              driver: local
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Crear el Dockerfile
      copy:
        dest: /home/ubuntu/docker-website/Dockerfile
        content: |
          FROM php:8.1-apache
          RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
          RUN a2enmod rewrite
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copiar los archivos de la página web
      copy:
        src: /home/admon/Automatizacion/Ansible/University
        dest: /home/ubuntu/docker-website/University
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        remote_src: no

    - name: Copiar el archivo init.sql
      copy:
        src: /home/admon/Automatizacion/Ansible/init.sql
        dest: /home/ubuntu/docker-website/init.sql
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        remote_src: no

    - name: Iniciar los servicios con Docker Compose
      command: docker-compose up -d --build
      args:
        chdir: /home/ubuntu/docker-website
