- name: Desplegar la página web en Docker con Apache y MySQL
  hosts: aws_instance
  become: true

  tasks:
    - name: Instalar Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Iniciar y habilitar Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Crear el directorio para Docker Compose
      ansible.builtin.file:
        path: /home/ubuntu/docker-website
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Obtener la última versión de Docker Compose
      command: >
        curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K[^"]*'
      register: compose_version

    - name: Descargar Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-{{ ansible_os_family | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clonar el repositorio de GitHub
      ansible.builtin.git:
        repo: 'https://github.com/felipe-estrada/Automatizacion.git'
        dest: /home/ubuntu/docker-website/University
        version: main

    - name: Crear archivo docker-compose.yml
      ansible.builtin.copy:
        dest: /home/ubuntu/docker-website/docker-compose.yml
        content: |
          version: '3'
          services:
            web:
              build: .
              container_name: php_apache_server
              volumes:
                - ./University:/var/www/html/
              ports:
                - "8080:80"
              depends_on:
                - db
            db:
              image: mysql:5.7
              container_name: mysql_db
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: rootpassword
                MYSQL_DATABASE: mydatabase
                MYSQL_USER: myuser
                MYSQL_PASSWORD: mypassword
              ports:
                - "3306:3306"
              volumes:
                - db_data:/var/lib/mysql
                - ./init.sql:/docker-entrypoint-initdb.d/init.sql
              healthcheck:
                test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
                interval: 10s
                timeout: 5s
                retries: 3
          volumes:
            db_data:
              driver: local
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Crear el Dockerfile
      ansible.builtin.copy:
        dest: /home/ubuntu/docker-website/Dockerfile
        content: |
          FROM php:8.1-apache
          RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
          RUN a2enmod rewrite
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copiar el archivo init.sql
      ansible.builtin.copy:
        src: /home/admon/Automatizacion/Ansible/init.sql
        dest: /home/ubuntu/docker-website/init.sql
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        remote_src: no

    - name: Iniciar los servicios con Docker Compose
      community.docker.docker_compose:
        project_src: /home/ubuntu/docker-website
        state: present
